#! /bin/sh

xrdb .Xresources


# Bspwm config
bspc monitor -d 一 二 三 四 五 六 七 八 九 十
bspc config border_width                2
bspc config window_gap                  15
bspc config normal_border_color         "#14161b"
bspc config focused_border_color        "#e44138"
bspc config pointer_follows_focus       false
bspc config split_ratio                 0.5
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config single_monocle              true
bspc config remove_unplugged_monitors	true
bspc config automatic_scheme            "alternate"

bspc config external_rules              "$HOME/.config/bspwm/external_rules"



# Autostart
xset r rate 250 30
setxkbmap us -option compose:ralt

killall -9 sxhkd redshift compton dunst polybar mpd transmission-daemon
sxhkd &
mpd &
polybar -r default &
redshift -P -c ~/.config/redshift/redshift.conf &
# compton --backend glx --paint-on-overlay --vsync opengl-swc & # fix tearing
compton -CGb &
transmission-daemon &
nm-applet &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

feh --bg-fill ~/Images/Wallpapers/papes/17.jpg # fallback

$HOME/.local/bin/pape
# files=(~/Images/Wallpapers/papes/*)
# sh -c "wal -s -i ${files[RANDOM % ${#files[@]}]} -g"
# # -b \"#14161b\" 
# #  ^ = to set backround manually
# 
# # source the colors.
# . "${HOME}/.cache/wal/colors.sh"
# 
# # Color settings with pywal
# 
# # reset the border colors.
# bspc config normal_border_color "$color0"
# bspc config active_border_color "$color2"
# bspc config focused_border_color "$color1"
# bspc config presel_feedback_color "$color1"
# 
# dunst \
# -lb "$color0" -lf "$color7" -lfr "$color1" \
# -nb "$color0" -nf "$color7" -nfr "$color1" \
# -cb "$color0" -cf "$color7" -cfr "$color1" &
# 
# sleep 0.5
# notify-send "Bspwm Loaded" "uwu"
